---
- name: Set router banners
  hosts: cisco_ios
  gather_facts: false

  tasks:
    - name: Load banner onto network device
      cisco.ios.ios_banner:
        banner: login
        text: |
          this is {{ inventory_hostname }}
          and is a {{ environment_var }} environment
        state: present
