---
- name: Retrieve facts for network infrastructure
  hosts: cisco_ios
  gather_facts: false

  tasks:
    - name: Load read interfaces role
      ansible.builtin.include_role:
        name: "../roles/facts"

- name: Build report with facts
  hosts: rhel.shared
  gather_facts: false

  tasks:

    - name: Build a report
      ansible.builtin.include_role:
        name: "../roles/build_report"
