---
- name: Reboot Cisco IOS device
  hosts: cisco_ios
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Save running config
      ios_config:
        save_when: modified

    - name: Reload the device
      ios_command:
        commands:
          - reload
      register: reload_response

    - name: Confirm reload
      ios_command:
        commands:
          - y
      when: "'Proceed with reload' in reload_response.stdout[0]"
