---
- name: Restore router configurations
  hosts: cisco_ios
  gather_facts: false

  tasks:
    - name: Retreive configuration from rhel.shared to execution environment
      ansible.builtin.fetch:
        src: "/backup/{{ rollback_date }}/{{ inventory_hostname }}.txt"
        dest: "/tmp/{{ rollback_date }}/"
        flat: true
      delegate_to: rhel.shared
      when: ansible_network_os is defined

    - name: Load restore role
      ansible.builtin.include_role:
        name: "../roles/restore"
      when: ansible_network_os is defined
