---
- name: Add/Remove SSH Public Key on Cisco IOS Device for Existing User
  hosts: cisco_ios
  gather_facts: false

  vars:
    ios_username: "cisco" 
    ios_ssh_public_key: "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBAeafq7FAvgM2Gmu+LfM130M3RCG+dUGoUm+WRBqcuyR1wmP8661Mhj/WoYSNjnYcpwm+cdWtEnsPXM8QXNzp1U= nlvand05@Denniss-MBP.fritz.box"
    remove_ssh_key: false

  tasks:
    - name: Add SSH public key to the existing local user
      cisco.ios.ios_user:
        name: "{{ ios_username }}"
        sshkey: "{{ ios_ssh_public_key | trim }}" 
        state: present 
      when: not remove_ssh_key
      
    - name: Remove SSH public key from the existing local user
      cisco.ios.ios_user:
        name: "{{ ios_username }}"
        sshkey: "{{ ios_ssh_public_key | trim }}" 
        state: absent 
      when: remove_ssh_key 
    - name: Save the running configuration to startup configuration
      cisco.ios.ios_config:
        save_when: always
