---
- name: Manage VLANs on switches
  hosts: cisco_ios_switches
  vars:
   vlan_definitions:
    - vlan_id: "{{ vlan_id | int }}" # Ensure vlan_id is treated as an integer
      name: "{{ vlan_name }}"
      subnet_ip: "172.16.{{ vlan_id | int }}.0"
      subnet_mask: "255.255.255.0" # Assuming a /24 subnet
      gateway_ip:
        R1: "172.16.{{ vlan_id | int }}.1"
        R2: "172.16.{{ vlan_id | int }}.2"
        VRRP: "172.16.{{ vlan_id | int }}.10" # VRRP virtual IP
  tasks:
    - name: Make sure the VLANs exist
      cisco.ios.ios_vlans:
        config: "{{ lookup('template', 'cisco_switch_vlans_config.j2') | from_yaml }}"
        state: merged
      register: config_changes

    - name: Display executed commands
      when: config_changes.commands
      ansible.builtin.debug:
        msg: "{{ config_changes.commands }}"
