---
- name: Gather info from Cisco IOS devices
  hosts: cisco_ios

  tasks:
    - name: Get config for IOS devices
      cisco.ios.ios_facts:
        gather_subset: all
      register: result

    - name: Display device OS versions
      ansible.builtin.debug:
        var: result

- name: Build report with facts
  hosts: rhel.shared
  gather_facts: false

  tasks:

    - name: Build a report
      ansible.builtin.include_role:
        name: "../roles/build_report"