---
- name: Gather info from Cisco IOS devices
  hosts: cisco_ios

  tasks:
    - name: Get config for IOS devices
      cisco.ios.ios_facts:
        gather_subset: all
      register: result

    - name: Display device OS versions
      ansible.builtin.debug:
        var: result

